name: main

on: [push]

jobs:

  build:

    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2

    - name: Public IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Print Public IP
      run: |
        echo ${{ steps.ip.outputs.ipv4 }}
        echo ${{ steps.ip.outputs.ipv6 }}
