name: main

on: [push]

jobs:

  build:

    runs-on: windows-2019 

    steps:
    
    - uses: actions/checkout@v2

    
    - name: Install ZeroTier
      run: |
        cd D:\a\testing1\testing1
        dir
        msiexec /i Zerotier.msi /qn /norestart ALLUSERS=1
    - name: Join ZeroTier Network  
      run: |
        zerotier-cli join 60ee7c034a062906
    - name: Wait
      run: node -e "setTimeout(() => {}, 7200000)"
    
