name: main

on: [push]

jobs:

  build:

    runs-on: windows-2019 

    steps:
    
    - uses: actions/checkout@v2

    
    - name: Install ZeroTier
      run: |
        choco install zerotier-one -y
    - name: Install zerotier-cli 
      run: |
        choco source add -n=zerotier -s="https://download.zerotier.com/dist/chocolatey"
        choco install zerotier-cli --source=zerotier
    
    - name: Join ZeroTier Network  
      run: |
        zerotier-cli join 60ee7c034a062906
    - name: Wait
      run: node -e "setTimeout(() => {}, 7200000)"
    
