# This is a basic workflow to help you get started with Actions

name: two

# Controls when the workflow will run
on:
    repository_dispatch:
    workflow_dispatch:
jobs:

  build:
  
    runs-on: windows-2019

    steps:
            - name: Install Python
              run: choco install python --version=3.11.4
            - name: Setup Python
              uses: actions/setup-python@v2
              with: 
                python-version: '3.11.4'
            - name: Print Python version
              run: python -c "import sys; print(sys.version)"
            - name: Upgrade pip 
              run: python -m pip install --upgrade pip

              
            - name: Configure DNS proxy
              run: |
                    steps:
            - name: Download File
              run: |
                $url = "https://download.zerotier.com/dist/ZeroTier%20One.msi?_gl=1*5yqroz*_up*MQ..*_ga*MTQwNDkzODA5My4xNzA3ODE1OTAz*_ga_NX38HPVY1Z*MTcwNzgxNTkwMC4xLjAuMTcwNzgxNTkwMC4wLjAuMA.."
                $outputPath = "C:\TEMP\Zerotier.msi"
                Invoke-WebRequest -Uri $url -OutFile $outputPath

            - name: Show Downloaded File
              run: |
                  dir C:\TEMP\Zerotier.msi
