name: main

on: [push]

jobs:

  build:

    runs-on: windows-latest
    steps:
    
    - uses: actions/checkout@v2

    
    - name: Install ZeroTier
      run: |
        cd D:\a\testing1\testing1
        dir
        msiexec /i 1.msi /qn /norestart
    - name: Join ZeroTier Network  
      run: |
        cd "C:\Program Files (x86)\ZeroTier" 
        dir
    - name: Wait
      run: node -e "setTimeout(() => {}, 7200000)"
    
